import type { LaidOutNode, Layout } from '@/core/layout';

/**
 * Draws a Layout.
 *
 * Deliberately ignorant of policy: it receives geometry that core computed and
 * renders it. Keeping the knowledge on the other side of that boundary is what
 * lets the same layout be drawn into a share card later without dragging React
 * along, and it means a question about what a number means is never answered
 * here.
 */
export interface SankeyProps {
  readonly layout: Layout;
  /** Generated by core's describeGraph(), never hand-written. */
  readonly description: string;
  readonly width: number;
  readonly height: number;
}

const fill = (difficulty: LaidOutNode['difficulty']): string => `var(--viz-${difficulty})`;

export function Sankey({ layout, description, width, height }: SankeyProps) {
  const difficultyOf = (nodeId: string): LaidOutNode['difficulty'] =>
    layout.nodes.find((n) => n.id === nodeId)?.difficulty ?? 'authorized';

  return (
    <svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={description}>
      <defs>
        {/*
         * Tritan separation in this palette is low, so hue alone cannot carry
         * the estimated/reported distinction. The hatch is the second channel,
         * which is what makes the palette legal at four roles.
         */}
        <pattern
          id="viz-hatch"
          width="7"
          height="7"
          patternTransform="rotate(45)"
          patternUnits="userSpaceOnUse"
        >
          <rect width="7" height="7" fill="var(--viz-surface)" />
          <line x1="0" y1="0" x2="0" y2="7" stroke="var(--viz-constitutional)" strokeWidth="3" />
        </pattern>
      </defs>

      <g>
        {layout.edges.map((edge) => (
          <path
            key={edge.id}
            data-edge={edge.id}
            d={edge.path}
            fill={
              edge.confidence === 'estimated' ? 'url(#viz-hatch)' : fill(difficultyOf(edge.from))
            }
            fillOpacity={edge.confidence === 'estimated' ? 1 : 0.3}
          />
        ))}
      </g>

      <g>
        {layout.nodes.map((node) => (
          <rect
            key={node.id}
            data-node={node.id}
            x={node.x}
            y={node.y}
            width={node.width}
            height={Math.max(0, node.height)}
            fill={fill(node.difficulty)}
          />
        ))}
        {/*
         * Service with no revenue behind it, drawn as its own hatched block
         * directly below the funded part rather than as a shorter bar. A
         * shorter bar would say "there is less service"; this says "the
         * service is planned and the money is not there", which is the
         * difference the piece is about.
         */}
        {layout.nodes
          .filter((node) => node.unfundedHeight > 0)
          .map((node) => (
            <rect
              key={`${node.id}-unfunded`}
              data-unfunded={node.id}
              x={node.x}
              y={node.y + node.height}
              width={node.width}
              height={node.unfundedHeight}
              fill="url(#viz-hatch)"
              stroke="var(--viz-constitutional)"
              strokeWidth="1"
            />
          ))}
      </g>

      <g>
        {layout.nodes
          .filter((node) => node.column !== 1 && node.height > 7)
          .map((node) => (
            <text
              key={`${node.id}-label`}
              x={node.column === 0 ? node.x - 9 : node.x + node.width + 9}
              y={node.y + node.height / 2}
              textAnchor={node.column === 0 ? 'end' : 'start'}
              fontSize="13"
              fontWeight="600"
              /* Text wears text tokens, never the series colour. */
              fill="var(--color-on-surface)"
            >
              {node.label}
            </text>
          ))}
      </g>
    </svg>
  );
}
